I = imread("coloured 3D MRI.jpg");
I1 = rgb2gray(I);
T = dctmtx(8);
f1 = @(block_struct) dct2(block_struct.data);
f2 = @(block_struct) idct2(block_struct.data);
B = blockproc(I1,[8 8],f1);
depth =find(abs(B) < 150);
B(depth) = zeros(size(depth));
B1 = blockproc(B,[8 8],f2)/255;
imwrite(B1,"compressed_img.jpg");
subplot(121);
imshow(I1);title("Original image");
subplot(122);
imshow(B1);title("Compressed image");
R = imfinfo("coloured 3D MRI.jpg");
r1 = R.FileSize;
R1 = imfinfo("compressed_img.jpg");
r2 = R1.FileSize;
compression_ratio = r1/r2;
disp("Compression ratio = ");disp(compression_ratio);